Create is-prime function
angus-c/just pull request #199
Opened 2020-10-04 15:59 UTC by EvandroLG

I added a function to check if a given number is prime or not.

2020-10-04 23:31 UTC, angus-c requested changes
Thanks this is great! Just a few nits

2020-10-04 23:31 UTC, angus-c commented on README.md
> +isPrime(1); // false
can you add examples for a) non integer numbers b) other types c) null/undefined, all of which should throw
(similar to https://github.com/angus-c/just/blob/master/packages/array-median/README.md#L13)

2020-10-04 23:31 UTC, angus-c commented on packages/number-is-prime/README.md
> +  isPrime(10); // false
same as other README

2020-10-04 23:31 UTC, angus-c commented on packages/number-is-prime/index.js
> +    throw new Error('Expected an integer');
`just-prime` expects an integer argument

2020-10-04 23:31 UTC, angus-c commented on packages/number-is-prime/index.js
> +    if (number % i === 0) return false;
house style is curly braces for all `if`s

2020-10-04 23:31 UTC, angus-c commented on test/number-is-prime/index.js
> +test('number is prime', function(t) {
also test for `0` and one large number, non integer numbers, other types, null/undefined

2020-10-07 15:59 UTC, angus-c requested changes
Sorry for late response! This looks great, just a couple of very small things. After that I will try to land and publish tonight

2020-10-07 15:59 UTC, angus-c commented on README.md
> +import modulo from "just-is-prime";
typo: isPrime not modulo

2020-10-07 15:59 UTC, angus-c commented on test/number-is-prime/index.js
> +  t.throws(function() {
could add a non-integer number here too

2020-10-07 20:23 UTC, EvandroLG commented on test/number-is-prime/index.js
> +  t.throws(function() {
@angus-c I'm testing against `undefined`, `function`, `string`, `object`, etc.

2020-10-08 16:17 UTC, angus-c approved these changes

2020-10-08 16:32 UTC, angus-c commented
Thanks!

2020-10-08 16:32 UTC, merged