Create array-permutations package
angus-c/just pull request #200
Opened 2020-10-14 20:40 UTC by EvandroLG

This function returns all permutations of the length N of the elements of a given Array.

2020-10-17 17:09 UTC, angus-c requested changes
Many thanks for this! Can you also patch bump version in array-group-by `package.json`

2020-10-17 17:09 UTC, angus-c commented on README.md
> +random(); // throws
`random()` -> `permutations()`

2020-10-17 17:09 UTC, angus-c commented on test/array-permutations/index.js
> +test('invalid', function(t) {
Also add test for `permutations()`

2020-10-20 18:05 UTC, EvandroLG commented on packages/array-permutations/index.js
> +  for (let i = 0; i < partialPermutations.length; i++) {
As far as I know the `length` is cached internally in modern engines.
That said, do you think it is still relevant to cache the `length`? If so, could I ask you why? :)

2020-10-20 18:37 UTC, angus-c commented on packages/array-permutations/index.js
> +  for (let i = 0; i < partialPermutations.length; i++) {
Well we also support older engines. In normal code I would not go so far as to cache length, but these utilities could be part of very hot code (called very often).

2020-10-21 18:26 UTC, EvandroLG commented on packages/array-permutations/index.js
> +  for (let i = 0; i < partialPermutations.length; i++) {
Okay. I also replaced `const` and `let` with `var`.

2020-10-24 17:35 UTC, merged

2020-10-24 17:45 UTC, angus-c commented
Landed: https://anguscroll.com/just/just-permutations
Thanks again!