Add cancel method to the debounce function
angus-c/just pull request #227
Opened 2021-04-09 10:04 UTC by EvandroLG

I refactored the debounce function a little bit, adding a method to cancel the debounced function.
If you - @angus-c - are okay with this implementation, afterwards I will add the same method in the throttle function as well.

2021-04-10 20:31 UTC, angus-c requested changes
Thank you!

Please also update `index.tests.ts` so it starts like this

```
// OK
debounce(() => {});
debounce(() => {}, 50);
debounce(() => {}, 200, true);
debounce(() => {}, 1000, false);

debounce(() => {}).cancel();
debounce(() => {}, 50).cancel();
debounce(() => {}, 200, true).cancel();
debounce(() => {}, 1000, false).cancel();

// not OK
// @ts-expect-error
debounce();
// @ts-expect-error
debounce().cancel();

[//etc...]
```

2021-04-10 20:31 UTC, angus-c commented on test/function-debounce/index.js
>  test('when callFirst is true, runs once, waits for n ms then runs again', function(
Can you add another test (positioned after "when CallFirst is true" test)

```
test('cancel debounced function when callFirst is true', function(t) {
  t.plan(1);

  var callCounter = 0;
  var fn = debounce(function() {
    callCounter++;
  }, 200, true);

  fn();
  fn();
  fn.cancel();

  setTimeout(function() {
    t.equal(callCounter, 1);
  }, 300);
});
```

2021-04-11 10:56 UTC, EvandroLG commented
Done!
Btw, how are you running the `index.test.ts` file? `ts-node`?

2021-04-11 18:34 UTC, angus-c commented
> Done!
> Btw, how are you running the `index.test.ts` file? `ts-node`?

Thanks! I’m AFK right now but will land/version/publish when I get a chance

I do `tsc <test name>` and try to remember to delete generated js before pushing 🤣(I guess I could add a got ignore for that pattern)

But also vscode linter highlights any ts errors  as I add them

2021-04-11 20:55 UTC, EvandroLG commented
Maybe, it would be nice to add a script to run those tests as we have for lint and unit tests. WDYT?

2021-04-11 23:29 UTC, angus-c commented
Yeah agree. I only looked into it very briefly. Not sure what the exit codes etc for that script are.

2021-04-12 00:15 UTC, merged

2021-04-12 00:25 UTC, angus-c commented
Published as function-debounce@1.4.0