just-random
angus-c/just pull request #251
Opened 2021-05-04 10:56 UTC by EvandroLG

It produces a random number between two values.

2021-05-04 16:35 UTC, angus-c requested changes
Thanks! We're going to have to rename this `just-random-number` because there is already a `just-random` for arrays.

Also I think it belongs in numbers section not function? I see why you did function section, but all current function utils take a function as an argument, and all current number utils take numbers

2021-05-04 16:35 UTC, angus-c commented on test/function-random/index.js
> +  t.ok(expected(random(5, 5, 10), 5, 10));
I think you added extra arg by mistake!

2021-05-04 16:35 UTC, angus-c commented on packages/function-random/package.json
> +  "main": "index.js",
Please add `"types": "index.d.ts",` under this line

2021-05-04 16:35 UTC, angus-c commented on test/function-random/index.js
> +test('returns a number from 0 to 5', function(t) {
Can you add one more test with negative arguments

2021-05-05 07:30 UTC, Masa-Shin commented
IMHO the name `number-random`  should be reserved for a package that helps to get random number (float) in a range. How about `number-random-int` or `number-random-integer` for the package?

2021-05-05 16:51 UTC, angus-c commented
@Masa-Shin I agree, `just-random-int` is good for package name and `number-random-int` for internal name

2021-05-08 05:31 UTC, angus-c approved these changes

2021-05-08 05:32 UTC, angus-c commented
Thank you!

2021-05-08 05:32 UTC, merged