Add types to array-index package
angus-c/just pull request #274
Opened 2021-05-24 23:45 UTC by dimfeld

2021-05-30 21:02 UTC, angus-c requested changes
A few tests things (sorry should have looked for these earlier)

2021-05-30 21:02 UTC, angus-c commented on packages/array-index/index.tests.ts
> +index([ { a: 5 }, { a: 6 } ], 'b');
this is valid (does not throw an error), just returns `{}`

2021-05-30 21:02 UTC, angus-c commented on packages/array-index/index.tests.ts
> +index([1, 2, 3], 'a');
this is valid (does not throw an error), just returns {}

2021-05-30 21:02 UTC, angus-c commented on packages/array-index/index.tests.ts
> +index([ { a: 5 }, { a: 6 } ], (o: number) => o.a);
I'd prefer not to use typescript in the test itself
So just
`index([ { a: 5 }, { a: 6 } ], (o) => o.a);`

2021-06-02 07:27 UTC, dimfeld commented
Thanks for the feedback! Made all three changes.

2021-06-05 19:01 UTC, merged