Adds inRange package
angus-c/just pull request #431
Opened 2022-03-19 12:49 UTC by EvandroLG

This PR is adding the inRange package, which was requested in issue #410 :)

2022-03-19 18:51 UTC, angus-c commented
Thanks @EvandroLG, great job! Just a few minor nits.

2022-03-21 10:17 UTC, EvandroLG commented
Which ones exactly @angus-c ? :D

2022-03-21 16:12 UTC, angus-c requested changes

2022-03-21 16:12 UTC, angus-c commented
> Which ones exactly @angus-c ? :D

Whoops I had forgotten to hit submit review! Apologies, should be there now

2022-03-21 20:30 UTC, EvandroLG commented on packages/number-in-range/index.d.ts
> +  end?: number
In TypeScript a required parameter can not follow an optional one :)

2022-03-27 06:36 UTC, angus-c commented on packages/number-in-range/index.d.ts
> +  end?: number
Ok that's fair. I'm not a TS expert :)

2022-03-27 06:36 UTC, merged