added `pipe` package
angus-c/just pull request #492
Opened 2022-08-22 07:46 UTC by TClark1011

NOTE: I did not rollup config because I wasn't sure how I should configure it

2022-08-27 19:44 UTC, angus-c requested changes
Thanks for this! Just a few small issues. Also did you run `yarn generate-readmes`? I would have expected updates to global README.ms too.

2022-08-27 19:44 UTC, angus-c commented on md-variables.json
> +  "just-flow": {
Rename `just-flow` to `just-pipe`

2022-08-27 19:44 UTC, angus-c commented on test/function-pipe/index.js
> +test('Throws if only give 0 or 1 parameters', function(t) {
can you add the fail case where second param is a non-function

2022-08-27 19:44 UTC, angus-c commented on test/function-pipe/index.js
> +  t.equal(pipe(3, addOne, double), 8);
Would also be good to tests with args 2 and 3 swapped

2022-09-18 23:27 UTC, TClark1011 commented
@angus-c requested changes have been made, sorry for the delay

2022-11-19 20:48 UTC, angus-c commented
Sorry for the even bigger delay from me! Thanks for making the changes. I still don't see a global README for some reason. I'm going to merge now anyway and try running the script myself—and the one for `.mjs` generation. Might not get to doing those updates it immediately, so it won't be published right away.
Thanks again!

2022-11-19 20:49 UTC, angus-c commented
Sorry for the even bigger delay from me! Thanks for making the changes. I still don't see a global README for some reason. I'm going to merge now anyway and try running the script myself—and the one for `.mjs` generation. Might not get to doing those updates it immediately, so it won't be published right away.
Thanks again!

2023-01-02 18:15 UTC, merged

2023-01-02 18:25 UTC, angus-c commented
Ok my bad it was there but not in alpha order so I didn't see in global README
Re-ordered https://github.com/angus-c/just/pull/529

2023-01-02 18:38 UTC, angus-c commented
Published as just-pipe@1.0.0

2023-01-02 18:47 UTC, angus-c commented
And now available in REPL
https://anguscroll.com/just/just-pipe