just-deep-omit
angus-c/just pull request #531
Opened 2023-01-14 19:24 UTC by cycle4passion

My first open source contribution.
I did my best to read and follow guidelines/code of conduct.
Tests are passing.
Readme's have been generated.

If I have done something wrong, just let me know.

2023-01-28 20:21 UTC, angus-c commented
Many thanks @cycle4passion! Sorry for the delay in reviewing this. 
Did you run `yarn generate-readmes`? It should update local and global README

2023-02-03 21:28 UTC, cycle4passion commented
yes, I did run it. I just tried again, and I get 

```js
 SJR  ~/Documents/Shared/Coding/just: yarn generate-readmes
yarn run v1.22.15
$ node scripts/generate-readmes.js
✨  Done in 0.24s.
```

It doesn't seem to update anything.

I previously updated `md-variables.json` too

```js
  "just-deep-omit": {
    "packageName": "just-deep-omit",
    "dir": "object-deep-omit",
    "description": "Omits deeply nested key/values from an object",
    "examples": [
      "import deepOmit from 'just-deep-omit';",
      "",
      "let obj = {a:3, b:{c:5, d:7}, e:[1,2,3]};",
      "omit(obj, 'b.c'); // {a:3, b:{d:7}, e:[1,2,3]};",
      "omit(obj, ['b','c']); // {a:3, b:{d:7}, e:[1,2,3]};",
      "omit(obj, 'e.1'); // {a: 3, b:{c:5, d:7}, e:[1,3]};"
    ]
  },
```

2023-02-04 20:37 UTC, angus-c reviewed
OK I'll try to fix the README after it's landed. I think it might require manually adding the initial link (I've forgotten 😅 )

Util looks sound but a few things here. (Biggest is I think it should return a new object instead of mutating, like just-omit does)

2023-02-04 20:37 UTC, angus-c commented on packages/object-deep-omit/CHANGELOG.md
> +# just-deep-omit
Not required for initial commit. It can be autocreated on the first update.

2023-02-04 20:37 UTC, angus-c commented on packages/object-deep-omit/LICENSE
> +Copyright (c) 2016 angus croll
2023, you can add your own name too

2023-02-04 20:37 UTC, angus-c commented on packages/object-deep-omit/index.cjs
> +omit(obj, ['a','b','c']); // {a:3, b:{d:7}, e:[1,2,3]};
above example is wrong

2023-02-04 20:37 UTC, angus-c commented on packages/object-deep-omit/index.cjs
> +function deepOmit(obj, propsArg) {
This util mutates in place and returns boolean
Original justOmit returns a mutated copy and preserves the original. I think we should be consistent with that

2023-02-04 20:37 UTC, angus-c commented on packages/object-deep-omit/index.tests.ts
> +const arr = ['one', 'two'];
Add case for shallow omit string which should still work 
const obj3 = {foo: 1, bar: 2}
// OK
deepOmit(obj3, 'foo')

2023-02-04 20:37 UTC, angus-c commented on packages/object-deep-omit/package.json
> +  "version": "4.2.0",
1.0.0

2023-02-04 20:37 UTC, angus-c commented on test/object-deep-omit/index.cjs
> +});
Add tests for:
1) throws on bad argument types
2) Simple shallow omit case which although not the focus of this util should still work

2023-02-04 20:51 UTC, angus-c requested changes

2023-02-04 20:51 UTC, angus-c commented on test/object-deep-omit/index.cjs
> +var deepOmit = require('../../../packages/object-deep-omit/index.cjs');
Looks like these paths are off (should be `'../../packages/object-deep-omit/index.cjs'` ?

2023-09-24 14:13 UTC, closed without merging